name: Docker Image CI

on:
  push:
    branches: [ "group-3" ]
  pull_request:
    branches: [ "group-3" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Client Docker image
      working-directory: ./client
      env:
          DOCKERHUB_USERNAME: ${{ secrets.GROUP3_DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.GROUP3_DOCKERHUB_ACCESS_TOKEN }}
      run: |
           docker build --tag $DOCKERHUB_USERNAME/assignment-2-agile-avengers:$(date +%s) .
           echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username $DOCKERHUB_USERNAME --password-stdin
           docker push $DOCKERHUB_USERNAME/my_repository_name:latest


    - name: Build the Server Docker image
      working-directory: ./server
      env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: |
           docker build --tag $DOCKERHUB_USERNAME/assignment-2-agile-avengers:$(date +%s) .
           echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username $DOCKERHUB_USERNAME --password-stdin
           docker push $DOCKERHUB_USERNAME/my_repository_name:latest
